import { create } from 'zustand'

export const useRoom = create((set) => ({
  players: [],
  settings: {},
  roomId: "",
  roomName: "",
  messages: [],
  myDetail: {},
  sktId: "",
  hostId:"",
  drawerId:"",
  drawWord:"",
  isChoosing:false,
  isPlaying:false,
  guessed:false,
  timer:0,
  roomDetail:{},
  round:0,
  words:[],
  verify:false,
  guessedPlayers:[],
  displayScore:false,
  notGuessedPlayers:[],
  displayFinalScore:false,
  hintsShown:0,


  setPlayers: (players) => set({ players }),
  setSettings: (settings) => set({ settings }),
  setRoomId: (roomId) => set({ roomId }),
  setRoomName: (roomName) => set({ roomName }),
  setMessages: (messages) => set({ messages }),
  setMyDetail: (myDetail) => set({ myDetail }),
  setSktId: (sktId) => set({ sktId }),
  setHostId: (hostId) => set({ hostId }),
  setDrawerId: (drawerId) => set({ drawerId}),
  setIsPlaying: (isPlaying) => set({ isPlaying }),
  setIsChoosing: (isChoosing) => set({ isChoosing }),
  setDrawWord: (drawWord) => set({drawWord}),
  setGuessed: (guessed) => set({guessed}),
  setTimer: (timer)=>set({timer}),
  setRoomDetail:(roomDetail)=>set({roomDetail}),
  setRound:(round)=>set({round}),
  setWords:(words)=>set({words}),
  setVerify:(verify)=>set({verify}),
  setGuessedPlayers:(guessedPlayers)=>set({guessedPlayers}),
  setDisplayScore:(displayScore)=>set({displayScore}),
  setNotGuessedPlayers:(notGuessedPlayers)=>set({ notGuessedPlayers }),
  setDisplayFinalScore:(displayFinalScore)=>set({displayFinalScore}),
  setHintsShown:(hintsShown)=>set({hintsShown}),


  resetRoom: () => set({
    players: [],
    settings: {},
    roomId: "",
    roomName: "",
    messages: [],
    myDetail: {},
    sktId:"",
    hostId:"",
    drawerId:"",
    drawWord:"",
    isChoosing: false,
    isPlaying: false,
    guessed: false,
    timer:0,
    roomDetail: {},
    round:0,
    words:[],
    verify: false,
    guessedPlayers:[],
    displayScore:false,
    notGuessedPlayers:[],
    displayFinalScore:false,
    hintsShown:0,
  })
}))
